---
title: "Selection"
output: 
  html_document:
    css: css\style.css
    runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr)
library(flextable)
```



```{r eruptions, echo=FALSE}

ui <- fluidPage(
  h3("The original population is assumed to be in Hardy-Weinberg equillibrium."),

h4("Select your original population allele frequencies.  (Must be between 0 and 1.)"),
  numericInput("p", label = "p = f(M)?", min = 0.00001, max = 0.99999, value = 0.5),

h4("Original population genotypic frequencies:"),
tableOutput("HW"),

br(),

h4("The selection weight for MM will be fixed at 1."),
  numericInput("wMM", label = "Selection weight for MM?",
              min = 1, max = 1, value = 1),
  numericInput("wMN", label = "Selection weight for MN?",
              min = 0, max = 100, value = 1),
  numericInput("wNN", label = "Selection weight for NN?",
              min = 0, max = 100, value = 1),

br(),

h3("You can press the button below to generate a new generation from this population with your given selection weights."),

tableOutput("gen")
)

server <- function(input, output, session) {
  output$gen <- renderTable({
    data.frame(Genotype = rep("Proportion", input$i+1), 
             MM = input$p^2, 
             MN = input$p*(1-input$p)*2, 
             NN = (1-input$p)^2, 
             Total = 1)
  })

  output$HW <- renderTable({
    data.frame(Genotype = c("Proportion"), MM = input$p^2, MN = input$p*(1-input$p)*2, NN = (1-input$p)^2, Total = 1)
    })
}
  
```